### ISSUE TITLE
404 https://cdn.cryptowat.ch/assets/build/scripts/dist/embed.js

### ISSUE THREAD

**Issue by nyg** [cryptowatch/embed#2]
The `embed.js` file is gone, therefore the demo doesn't work... I also used it for one of my "apps". Could you put it back on your CDN?

Thanks! :)

**Comment by ddaws** [comment]
Thanks for flagging this. We have moved our scripts and embed is now available at `https://static.cryptowat.ch/assets/scripts/embed.bundle.js`. I will update this repo accordingly.

**Comment by nyg** [comment]
Thanks a lot! Works great now ;).
